### ISSUE TITLE
Inner shadows mislabeled

### ISSUE THREAD

**Issue by brittneypostma** [argyleink/open-props#139] opened 2021-12-30 16:10 UTC
Inner shadows are labeled out of order, should be (0-4), instead we have 0 then jumps to 7-10.
![image](https://user-images.githubusercontent.com/45889730/147768719-d85b96ad-a97c-4038-8c01-8b4871c8a560.png)

**Comment by argyleink** [comment] 2021-12-30 23:28
oh! dang css counters look like they reset to 0 then resume(?) at 7 lol, i'll check it out!

**Comment by argyleink** [comment] 2021-12-30 23:29
oh, which browser?

**Comment by argyleink** [comment] 2021-12-30 23:31
looks like only Firefox reproduces this bug.. might be a CSS counters bug in Firefox?

**Comment by brittneypostma** [comment] 2022-01-01 03:26
Sorry, just seeing these, yes I was in FireFox Dev, that is interesting.

**Comment by argyleink** [comment] 2022-01-10 00:29
fixed by #145

**Closed by argyleink** 2022-01-10 00:29 UTC
