### ISSUE TITLE
--radius-conditional 1e5 syntax doesn't work in Firefox

### ISSUE THREAD

**Issue by wcDogg** [argyleink/open-props#448] opened 2023-12-15 00:50 UTC
Here is a Codepen showing the issue: https://codepen.io/wcDogg/pen/bGzPwpw

In Firefox 120.0.1,  no  radius  is applied when using this:

```
--radius-1e5: clamp(0px, calc(100vw - 100%) * 1e5, var(--radius-4));
```

However, this does work:

```
--radius-9999: clamp(0px, calc(100vw - 100%) * 9999, var(--radius-4)); 
```

**Comment by argyleink** [comment] 2023-12-15 15:57
hmmm... that scientific notation is old school, sounds like a regression in firefox? i'll do some investigation on this, thanks!

**Comment by argyleink** [comment] 2023-12-15 16:27
hehe, `1e3` and `1e4` work, but not anything `1e5` and above 🤦🏻

**Comment by argyleink** [comment] 2023-12-15 16:40
https://bugzilla.mozilla.org/show_bug.cgi?id=1870297

**Comment by argyleink** [comment] 2023-12-15 16:41
so i guess, until that bug is fixed (and maybe just forever), we make all the calc's use `1e4`…?

**Comment by wcDogg** [comment] 2023-12-15 18:04
Glad the answer was easy to find - I didn't even think of trying 1e3 or 1e4. Should I close this?

**Comment by argyleink** [comment] 2023-12-15 18:33
i was going to say leave it open.. but it seems that the calc() in firefox is fine with the 1e5 notation, when it's inside a custom property 🤔 

https://codepen.io/argyleink/pen/yLZdjrE/56b6355cf0248aff95e6923e70f76b8f

like, the OP library vars dont seem to fail. can you confirm that? if so, we can close this

**Comment by wcDogg** [comment] 2023-12-15 19:41
Sorry - not sure what the ask is? But, if you open that pen in Firefox, `--radius-conditional-3` is not working.

**Comment by wcDogg** [comment] 2023-12-15 19:44
Is the ask to try an OP variable directly like this?  No love in Firefox.

https://codepen.io/wcDogg/pen/GRzbGxO

**Comment by argyleink** [comment] 2023-12-15 20:31
**for me just now:**
Firefox 120 - shows this bug
Firefox 121 - this bug doesnt happen

which version are you testing in?

**Comment by wcDogg** [comment] 2023-12-15 23:56
Firefox 120.0.1

**Comment by argyleink** [comment] 2023-12-16 17:50
wanna try 121 and verify the bug is gone? then we can just close this as a temporary firefox regression of 120

**Comment by wcDogg** [comment] 2023-12-16 18:53
Sorry, no - Firefox says I'm up to date with 12.0.1 - I even tried reinstalling it.  I'm on Windows 11

**Comment by argyleink** [comment] 2024-01-02 18:01
looks like they fixed it https://bugzilla.mozilla.org/show_bug.cgi?id=1870297

**Closed by argyleink** 2024-01-02 18:01 UTC
